### ISSUE TITLE
Best enumeration update

### ISSUE THREAD

**Issue by MaximAdler** [RihaMaheshwari/OSCP-Preparation#2]
> Best Enumeration - http://www.0daysecurity.com/penetration-testing/enumeration.html

The link is not accessible anymore.

I have updated all links and wrote all content to the `.md` file, so you can just link to it.
Here is the link: https://github.com/MaximAdler/pentest-helper/blob/main/enumeration.md

**Comment by MaximAdler** [comment]
Any updates here?

**Comment by RihaMaheshwari** [comment]
Added/Closed

**Comment by RihaMaheshwari** [comment]
Closed
